### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by getglad** [chadhuber/citysdk-node#1]
I am looking into making a PR that would add some error handling to this project - particularly if `jsonpRequest` response.statusCode is a 400 (utils.js line 18). I am having trouble following all the callback methods, however. Any thoughts on how to manage that process?

**Comment by getglad** [comment]
So from what I can tell, at least my issue is coming from submitting invalid zip codes through `ZIPtoLatLng` (census.js, line 1004). The service responds to invalid zip code with an empty `features` property.

So, line 1018 `if("features" in response)` resolves as false, `returnValue.lat` and `returnValue.lng` are never updated, leaving `request.lat` and `request.lng` null on lines 1500/1501.

This results in `latLngToFIPS` setting both `x` and `y` to null on line 955, making your request to `utils.jsonpRequest` result in a `400` error, and `body` will be HTML.

As you attempt to parse the returned object, you're going to start throwing errors as you access properties that are not there. Example is in `this.latLngToFIPS`, line 1538 - `geographies` will not have `2010 Census Blocks`.

Long term, it probably would be a good idea to add more `.hasOwnProperty` checks.

My short term suggestion would be in census.js, line 1500 (where I found the problem) and line 1263 (where you are doing a similar process, but I haven't backed into why it's repeated):

```
request.lat = response.lat === null ? 0 : response.lat;
request.lng = response.lng === null ? 0 : response.lng;
if(!request.lat && !request.lng) {
  request.data = []
  callback(request);
} else
  _this.APIRequest(request, callback);
```

Then in `GEORequest`, line 1692:

```
if("data" in request || !("variables" in request)) {
  if(!request.lat && !request.lng) {
    callback('error code');
  } else {
    _this.tigerwebRequest(request, function(response) {
    ...
```

This helps saves you from an unrecoverable error due to invalid zipcodes, and will let you return an error code instead, which can be processed by the client.

Any ideas on improvement?

**Comment by chadhuber** [comment]
@getglad Thanks for the comments. I agree that more .hasOwnProperty checks are in order plus some error catching for utils.js

Let me dive into the code with your comments in mind this evening and I'll write back something a bit more substantial

**Comment by getglad** [comment]
Sure thing. I've copied down positive and negative response URLs as examples:

Positive by Zip:
http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/2/query?where=ZCTA5%3D60613&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=CENTLAT%2CCENTLON&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

Negative (JSON w/o CENTLAT/CENTLON) by Zip:
http://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer/2/query?where=ZCTA5%3D06720&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=CENTLAT%2CCENTLON&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson

Postive by Lat/Lng:
http://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-090.0037279&y=+35.1325491&benchmark=4&vintage=4&layers=8,12,28,86,84&format=jsonp

Negative (HTML) by Lat/Lng (caused by empty lat/lng in the `By Zip` example):
http://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=null&y=null&benchmark=4&vintage=4&layers=8,12,28,86,84&format=jsonp

Also, I realized I got a couple of my original notes wrong, I'm updating/editing it now.
