### ISSUE TITLE
Update year to 2014

### ISSUE THREAD

**Issue by atsepkov** [chadhuber/citysdk-node#4]
It seems this version does not fetch 2014 data, (2013 being the most recent year it uses). `acs1` and `acs5` datasets both contain 2014 data now. Unless I'm misunderstanding something, the only needed updates for this are in https://github.com/chadhuber/citysdk-node/blob/master/lib/census.js:

    CensusModule.prototype.DEFAULT_YEAR = 2014

and

    CensusModule.prototype.acsyears = {
        "2010": ["acs5"],
        "2011": ["acs5"],
        "2012": ["acs5", "acs3", "acs1"],
        "2013": ["acs5", "acs3", "acs1"],
        "2014": ["acs5", "acs1"]
    }

On a related note, I was wondering if you knew the difference between the datasets. For example, there are datasets that go back to 1990, but they're not acs ones. Similarly, there is a 2015 and 2016 dataset (https://www.census.gov/data/developers/data-sets/popest-popproj.html) yet I don't know of a way to access it through CitySdk.

**Comment by chadhuber** [comment]
Updated. Thank you, appreciate it.

Regarding 2015 and 2016, my understanding is that CitySDK must do some type of data import from the raw Census data to make it available through the API. Opening an issue on their [project](https://github.com/CommerceDataService/citysdk) might help on that front.

And as to the the difference between acs5 and asc3.. unfortunately, I just don't know

**Comment by atsepkov** [comment]
Apparently 2015 data (acs5 and acs1) has been recently posted as well (https://www.census.gov/programs-surveys/acs/news/data-releases/2015/release.html#par_textimage_0), I just tested it to work in my local version for acs5.
